spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webeditor
    password: 123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    path: /api
  port: 8080
docker-client:
  url: http://localhost:2375
  connection-pool-size: 1000
file-config:
  base-path: file:/E:/filesystems-test
logging:
  path: E:/log
