spring:
  profiles:
    active: dev
  jpa:
    open-in-view: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false