spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webeditor
    password: 123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
server:
  servlet:
    path: /api