spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webeditor
    password: 123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  servlet:
    path: /api